server:
  port: 9020

spring:
  application:
    name: explore-zuul-server
  profiles:
    active: '@profiles.active@'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true
    
zuul:  routes:
    member-api:
      path: /member/**
      service-id: explore-member-service
      